#!/bin/bash

case "$dwm_theme" in
    gruvbox) colors="-nf #D5C4A1 -nb #262626 -sf #262626 -sb #f59542" ;;
    nord) colors="-nb #2E3440 -nf #88C0D0 -sb #4C566A -sf #33ccff" ;;
esac

steam="gamemoderun mangohud STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/bin/steam STEAM_COMPAT_DATA_PATH=/home/erik/Drives/NVMe/SteamLibrary/steamapps/compatdata"

proton="GE-Proton8-20"

instances="MO2SSE\nMO2FNV\nMO2FO3\nMO2FO4\nMO2OBV"

chosen=$(echo -e "$instances" | dmenu -c -l 5 $colors)

case "$chosen" in
    MO2SSE) $steam/489830/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run /home/erik/Drives/NVMe/Games/MO2SSE/ModOrganizer.exe ;;
    MO2FNV) $steam/22380/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run /home/erik/Drives/NVMe/Games/MO2FNV/ModOrganizer.exe ;;
    MO2FO3) $steam/489830/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run /home/erik/Drives/NVMe/Games/MO2FO3/ModOrganizer.exe ;;
    MO2FO4) $steam/377160/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run /home/erik/Drives/NVMe/Games/MO2FO4/ModOrganizer.exe ;;
    MO2OBV) $steam/489830/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run /home/erik/Drives/NVMe/Games/MO2OBV/ModOrganizer.exe ;;
esac
