#!/bin/bash
STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/bin/steam STEAM_COMPAT_DATA_PATH=/home/erik/Drives/NVMe/SteamLibrary/steamapps/compatdata/22380 /home/erik/.steam/root/compatibilitytools.d/GE-Proton8-16/proton run /home/erik/Drives/NVMe/Games/MO2FNV/nxmhandler.exe "$1"
