#!/bin/bash
STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/bin/steam STEAM_COMPAT_DATA_PATH=/home/erik/Drives/NVMe/SteamLibrary/steamapps/compatdata/1091500 $PROTON/proton run /home/erik/Drives/NVMe/Games/MO2\ Instances/Cyberpunk/nxmhandler.exe "$1"
