#!/bin/bash
STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/bin/steam STEAM_COMPAT_DATA_PATH=/home/erik/Drives/NVMe/SteamLibrary/steamapps/compatdata/1091500 /home/erik/.steam/root/compatibilitytools.d/GE-Proton8-22/proton run /home/erik/Drives/NVMe/Games/MO2CP2077/nxmhandler.exe "$1"
