#!/bin/bash
STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/bin/steam STEAM_COMPAT_DATA_PATH=/home/erik/Drives/NVMe/SteamLibrary/steamapps/compatdata/22380 $PROTON/proton run /home/erik/Drives/NVMe/Games/MO2\ Instances/New\ Vegas/nxmhandler.exe "$1"
