#!/usr/bin/env bash

lines="-l 20"

selected="$(ps -a -u $USER | \
            dmenu -p "Type to search and select process to kill" -z 850\
            $lines | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dmenu -p "$selected will be killed, are you sure?" -z 550\
            $lines)"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
