#!/bin/bash

steam="gamemoderun mangohud STEAM_COMPAT_CLIENT_INSTALL_PATH=/usr/bin/steam STEAM_COMPAT_DATA_PATH=/home/erik/Drives/NVMe/SteamLibrary/steamapps/compatdata"

nvmeGames="/home/erik/Drives/NVMe/Games/"

proton="GE-Proton8-21"

instances="Skyrim Special Edition\nFallout New Vegas\nFallout 3\nFallout 4\nOblivion"

chosen=$(echo -e "$instances" | dmenu -c -l 5)

case "$chosen" in
    "Skyrim Special Edition") $steam/489830/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run $nvmeGames/MO2SSE/ModOrganizer.exe ;;
    "Fallout New Vegas") $steam/22380/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run $nvmeGames/ModOrganizer.exe ;;
    "Fallout 3") $steam/489830/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run $nvmeGames/MO2FO3/ModOrganizer.exe ;;
    "Fallout 4") $steam/377160/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run $nvmeGames/MO2FO4/ModOrganizer.exe ;;
    "Oblivion") $steam/489830/ /home/erik/.steam/root/compatibilitytools.d/$proton/proton run $nvmeGames/MO2OBV/ModOrganizer.exe ;;
esac
